services:
  ocr-pipeline:
    extends:
      file: ocr-pipeline/docker-compose-ocr-pipeline.yml
      service: ocr-pipeline

# Define Networks
networks:
  sd-network:
    driver: bridge
    external: true