services:
  ocr-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr-pipeline
    ports:
      - "5001:5001"
    env_file:
      - ../.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_CASH_RELEASE_BUCKET=${S3_CASH_RELEASE_BUCKET}
      - S3_OCR_PIPELINE_BUCKET=${S3_OCR_PIPELINE_BUCKET}
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
      - SQS_DLQ_URL=${SQS_DLQ_URL}
    volumes:
      - /tmp:/tmp
    networks:
      - sd-network

networks:
  sd-network:
    name: sd-network
    external: true