services:
  ocr-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr-app
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - ep_stage_db_user=${ep_stage_db_user}
      - ep_stage_db_password=${ep_stage_db_password}
      - ep_stage_db_host=${ep_stage_db_host}
      - ep_stage_db_port=${ep_stage_db_port}
      - ep_stage_db=${ep_stage_db}
      - PGPASSWORD=${ep_stage_db_password}
    env_file:
      - ../.env
    volumes:
      - ../logs:/app/logs
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    networks:
      - sd-network

networks:
  sd-network:
    external: true